# Generated by Django 6.0.5 on 2026-05-06 02:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Criterion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('weight', models.DecimalField(decimal_places=4, max_digits=5)),
                ('type', models.CharField(choices=[('benefit', 'Benefit'), ('cost', 'Cost')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('field_key', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'criteria',
            },
        ),
    ]
