# Generated by Django 6.0.5 on 2026-05-06 02:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=100)),
                ('target_table', models.CharField(max_length=100)),
                ('target_id', models.CharField(blank=True, max_length=50, null=True)),
                ('details', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ProfileChangeLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_type', models.CharField(choices=[('HOUSEHOLD', 'Household'), ('FAMILY', 'Family'), ('BENEFICIARY', 'Beneficiary'), ('INDICATOR', 'Indicator')], max_length=15)),
                ('target_id', models.CharField(max_length=50)),
                ('action', models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated'), ('SOFT_DELETED', 'Soft Deleted'), ('RESTORED', 'Restored')], max_length=15)),
                ('changed_fields', models.JSONField(default=dict)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'profile_change_logs',
                'ordering': ['-changed_at'],
            },
        ),
    ]
