# Generated by Django 6.0.5 on 2026-05-06 02:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audit', '0001_initial'),
        ('beneficiaries', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profilechangelog',
            name='changed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profile_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profilechangelog',
            name='household',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='change_logs', to='beneficiaries.household'),
        ),
    ]
