# Generated by Django 6.0.5 on 2026-06-04 02:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CycleApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('application_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('selected', 'Selected'), ('deferred', 'Deferred')], default='applied', max_length=10)),
                ('computed_score', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('rank_position', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cycle_applications',
            },
        ),
        migrations.CreateModel(
            name='DailyParticipationRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('work_date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'Present / Worked'), ('absent', 'Absent / No Work'), ('excused', 'Excused')], default='present', max_length=10)),
                ('hours_worked', models.DecimalField(decimal_places=2, default=8, max_digits=4)),
                ('remarks', models.TextField(blank=True, default='')),
                ('photo', models.FileField(blank=True, null=True, upload_to='daily_participation_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'daily_participation_records',
                'ordering': ['work_date'],
            },
        ),
        migrations.CreateModel(
            name='ParticipationRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=255)),
                ('days_worked', models.PositiveIntegerField()),
                ('participation_start', models.DateField()),
                ('participation_end', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'participation_records',
            },
        ),
        migrations.CreateModel(
            name='ProgramCycle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cycle_name', models.CharField(max_length=255, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('work_start_date', models.DateField(blank=True, null=True)),
                ('work_end_date', models.DateField(blank=True, null=True)),
                ('slots', models.PositiveIntegerField(default=0)),
                ('max_per_household', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'program_cycles',
            },
        ),
    ]
