# Generated by Django 6.0.5 on 2026-05-06 02:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CycleApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('application_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('selected', 'Selected'), ('deferred', 'Deferred')], default='applied', max_length=10)),
                ('computed_score', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('rank_position', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cycle_applications',
            },
        ),
        migrations.CreateModel(
            name='ParticipationRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=255)),
                ('days_worked', models.PositiveIntegerField()),
                ('participation_start', models.DateField()),
                ('participation_end', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'participation_records',
            },
        ),
        migrations.CreateModel(
            name='ProgramCycle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cycle_name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('slots', models.PositiveIntegerField(default=0)),
                ('max_per_household', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'program_cycles',
            },
        ),
    ]
