# Generated by Django 6.0.5 on 2026-05-06 02:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beneficiaries', '0002_initial'),
        ('cycles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cycleapplication',
            name='applied_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marked_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cycleapplication',
            name='beneficiary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='beneficiaries.beneficiary'),
        ),
        migrations.AddField(
            model_name='participationrecord',
            name='beneficiary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participation_records', to='beneficiaries.beneficiary'),
        ),
        migrations.AddField(
            model_name='participationrecord',
            name='recorded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_participations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='programcycle',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_cycles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='participationrecord',
            name='cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participation_records', to='cycles.programcycle'),
        ),
        migrations.AddField(
            model_name='cycleapplication',
            name='cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='cycles.programcycle'),
        ),
        migrations.AlterUniqueTogether(
            name='cycleapplication',
            unique_together={('beneficiary', 'cycle')},
        ),
    ]
