# Generated by Django 6.0.5 on 2026-05-25 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycles', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programcycle',
            name='cycle_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
