# Generated by Django 6.0.5 on 2026-05-25 19:39

from django.db import migrations, models


def copy_existing_cycle_period_to_work_period(apps, schema_editor):
    ProgramCycle = apps.get_model('cycles', 'ProgramCycle')
    for cycle in ProgramCycle.objects.all():
        cycle.work_start_date = cycle.start_date
        cycle.work_end_date = cycle.end_date
        cycle.save(update_fields=['work_start_date', 'work_end_date'])


class Migration(migrations.Migration):

    dependencies = [
        ('cycles', '0003_alter_programcycle_cycle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='programcycle',
            name='work_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='programcycle',
            name='work_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RunPython(copy_existing_cycle_period_to_work_period, migrations.RunPython.noop),
    ]
