# Generated by Django 6.0.5 on 2026-05-25 22:31

import django.db.models.deletion
import uuid
from datetime import timedelta
from django.conf import settings
from django.db import migrations, models


def create_daily_rows_for_existing_participation(apps, schema_editor):
    ParticipationRecord = apps.get_model('cycles', 'ParticipationRecord')
    DailyParticipationRecord = apps.get_model('cycles', 'DailyParticipationRecord')
    rows = []
    for participation in ParticipationRecord.objects.all():
        current = participation.participation_start
        remaining_present = participation.days_worked
        while current <= participation.participation_end:
            is_present = remaining_present > 0
            rows.append(DailyParticipationRecord(
                participation_id=participation.id,
                work_date=current,
                status='present' if is_present else 'absent',
                hours_worked=8 if is_present else 0,
                remarks='Backfilled from summary participation record.',
                recorded_by_id=participation.recorded_by_id,
            ))
            if is_present:
                remaining_present -= 1
            current += timedelta(days=1)
    DailyParticipationRecord.objects.bulk_create(rows)


class Migration(migrations.Migration):

    dependencies = [
        ('cycles', '0004_programcycle_work_end_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyParticipationRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('work_date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'Present / Worked'), ('absent', 'Absent / No Work'), ('excused', 'Excused')], default='present', max_length=10)),
                ('hours_worked', models.DecimalField(decimal_places=2, default=8, max_digits=4)),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_records', to='cycles.participationrecord')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_daily_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'daily_participation_records',
                'ordering': ['work_date'],
                'unique_together': {('participation', 'work_date')},
            },
        ),
        migrations.RunPython(create_daily_rows_for_existing_participation, migrations.RunPython.noop),
    ]
