# Generated by Django 6.0.5 on 2026-05-25 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycles', '0005_dailyparticipationrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyparticipationrecord',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='daily_participation_photos/'),
        ),
    ]
