# Generated by Django 6.0.5 on 2026-06-04 02:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('head', 'Head'), ('spouse', 'Spouse'), ('child', 'Child'), ('parent', 'Parent'), ('sibling', 'Sibling'), ('relative', 'Relative')], max_length=10)),
                ('is_household_head', models.BooleanField(default=False)),
                ('first_name', models.CharField(blank=True, default='', max_length=100)),
                ('middle_name', models.CharField(blank=True, default='', max_length=100)),
                ('last_name', models.CharField(blank=True, default='', max_length=100)),
                ('full_name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, default='')),
                ('birthdate', models.DateField()),
                ('age', models.PositiveIntegerField(default=0)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('civil_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('widowed', 'Widowed'), ('separated', 'Separated'), ('live_in', 'Live-in')], max_length=10)),
                ('contact_number', models.CharField(blank=True, default='', max_length=20)),
                ('sectors', models.JSONField(blank=True, default=list)),
                ('is_tupad_eligible', models.BooleanField(default=False)),
                ('monthly_income', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('employment_status', models.CharField(choices=[('unemployed', 'Unemployed'), ('displaced_terminated', 'Displaced/Terminated'), ('underemployed', 'Underemployed'), ('self_employed_informal', 'Self-Employed/Informal'), ('employed', 'Employed'), ('student', 'Student'), ('retired', 'Retired'), ('pwd_unable_to_work', 'PWD / Unable to Work')], default='unemployed', max_length=25)),
                ('household_size', models.PositiveIntegerField(default=1)),
                ('lot_area_sqm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('num_dependents', models.PositiveIntegerField(default=0)),
                ('housing_condition', models.CharField(choices=[('makeshift', 'Makeshift/Informal Settler'), ('semi_permanent', 'Semi-Permanent'), ('permanent_deteriorating', 'Permanent but Deteriorating'), ('permanent_good', 'Permanent Good Condition'), ('informal_settler', 'Informal Settler'), ('semi_permanent_housing', 'Semi-Permanent Housing'), ('permanent_good_condition', 'Permanent Housing (Good Condition)'), ('permanent_needs_repair', 'Permanent Housing (Needs Repair)'), ('under_construction', 'Under Construction'), ('condemned_unsafe', 'Condemned / Unsafe Structure')], default='makeshift', max_length=25)),
                ('structure_condition', models.CharField(blank=True, choices=[('concrete', 'Concrete House (Concrete Structure)'), ('semi_concrete', 'Semi-Concrete House (Concrete and Wood Combination)'), ('wooden', 'Wooden House (Primarily Wood Materials)'), ('light_materials', 'Light Materials House (Nipa, Bamboo, Yero, Plywood, etc.)'), ('mixed_materials', 'Mixed Materials House (Combination of Various Materials)')], default='', max_length=30)),
                ('tenure_status', models.CharField(blank=True, choices=[('homeowner', 'Homeowner'), ('renter_tenant', 'Renter / Tenant'), ('living_with_relatives', 'Living with Relatives'), ('informal_settler', 'Informal Settler'), ('government_housing_beneficiary', 'Government Housing Beneficiary')], default='', max_length=40)),
                ('electrical_condition', models.CharField(blank=True, choices=[('legal_canoreco', 'Legally Connected to Electric Utility (CANORECO)'), ('shared_meter', 'Shared Meter / Sub-metered Connection'), ('unauthorized_connection', 'Unauthorized Electrical Connection'), ('no_service', 'No Electrical Service Access'), ('unstable_supply', 'Unstable Electrical Supply')], default='', max_length=35)),
                ('water_source', models.CharField(blank=True, choices=[('private_connection', 'Private Water Connection'), ('shared_connection', 'Shared Water Connection'), ('community_system', 'Community Water System'), ('deep_well', 'Deep Well / Own Well'), ('hand_pump', 'Hand Pump'), ('refilling_station', 'Water Refilling Station'), ('no_regular_supply', 'No Regular Water Supply')], default='', max_length=35)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'beneficiaries',
            },
        ),
        migrations.CreateModel(
            name='BeneficiaryIndicator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.DecimalField(decimal_places=4, max_digits=12)),
                ('raw_value', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'beneficiary_indicators',
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('family_number', models.PositiveIntegerField()),
                ('monthly_income_bracket', models.CharField(choices=[('NO_INCOME', 'No Income'), ('BELOW_5K', 'Below ₱5,000'), ('5K_10K', '₱5,000 – ₱10,000'), ('10K_20K', '₱10,000 – ₱20,000'), ('20K_30K', '₱20,000 – ₱30,000'), ('30K_50K', '₱30,000 – ₱50,000'), ('ABOVE_50K', 'Above ₱50,000'), ('UNSPECIFIED', 'Unspecified')], default='UNSPECIFIED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'families',
            },
        ),
        migrations.CreateModel(
            name='Household',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('household_code', models.CharField(max_length=50, unique=True)),
                ('address', models.TextField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('VACANT', 'Vacant'), ('ABANDONED', 'Abandoned'), ('DEMOLISHED', 'Demolished')], default='ACTIVE', max_length=15)),
                ('purok', models.CharField(blank=True, default='', max_length=100)),
                ('house_no_or_blk_lot_no', models.CharField(blank=True, default='', max_length=100)),
                ('street_name', models.CharField(blank=True, default='', max_length=150)),
                ('purok_sitio', models.CharField(blank=True, default='', max_length=150)),
                ('landmark', models.CharField(blank=True, default='', max_length=255)),
                ('length_of_residency', models.PositiveIntegerField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'households',
            },
        ),
    ]
