# Generated by Django 6.0.5 on 2026-05-06 02:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('head', 'Head'), ('spouse', 'Spouse'), ('child', 'Child'), ('parent', 'Parent'), ('sibling', 'Sibling'), ('relative', 'Relative')], max_length=10)),
                ('is_household_head', models.BooleanField(default=False)),
                ('full_name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, default='')),
                ('birthdate', models.DateField()),
                ('age', models.PositiveIntegerField(default=0)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('civil_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('widowed', 'Widowed'), ('separated', 'Separated'), ('live_in', 'Live-in')], max_length=10)),
                ('contact_number', models.CharField(blank=True, default='', max_length=20)),
                ('sectors', models.JSONField(blank=True, default=list)),
                ('is_tupad_eligible', models.BooleanField(default=False)),
                ('monthly_income', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('employment_status', models.CharField(choices=[('unemployed', 'Unemployed'), ('displaced_terminated', 'Displaced/Terminated'), ('underemployed', 'Underemployed'), ('self_employed_informal', 'Self-Employed/Informal'), ('employed', 'Employed')], default='unemployed', max_length=25)),
                ('household_size', models.PositiveIntegerField(default=1)),
                ('num_dependents', models.PositiveIntegerField(default=0)),
                ('housing_condition', models.CharField(choices=[('makeshift', 'Makeshift/Informal Settler'), ('semi_permanent', 'Semi-Permanent'), ('permanent_deteriorating', 'Permanent but Deteriorating'), ('permanent_good', 'Permanent Good Condition')], default='makeshift', max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'beneficiaries',
            },
        ),
        migrations.CreateModel(
            name='BeneficiaryIndicator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.DecimalField(decimal_places=4, max_digits=12)),
                ('raw_value', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'beneficiary_indicators',
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('family_number', models.PositiveIntegerField()),
                ('monthly_income_bracket', models.CharField(choices=[('NO_INCOME', 'No Income'), ('BELOW_5K', 'Below ₱5,000'), ('5K_10K', '₱5,000 – ₱10,000'), ('10K_20K', '₱10,000 – ₱20,000'), ('20K_30K', '₱20,000 – ₱30,000'), ('30K_50K', '₱30,000 – ₱50,000'), ('ABOVE_50K', 'Above ₱50,000'), ('UNSPECIFIED', 'Unspecified')], default='UNSPECIFIED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'families',
            },
        ),
        migrations.CreateModel(
            name='Household',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('household_code', models.CharField(max_length=50, unique=True)),
                ('address', models.TextField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('VACANT', 'Vacant'), ('ABANDONED', 'Abandoned'), ('DEMOLISHED', 'Demolished')], default='ACTIVE', max_length=15)),
                ('purok', models.CharField(blank=True, default='', max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'households',
            },
        ),
    ]
