# Generated by Django 6.0.5 on 2026-05-06 02:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beneficiaries', '0001_initial'),
        ('criteria', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deletions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='encoded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encoded_beneficiaries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_beneficiaries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='beneficiaryindicator',
            name='beneficiary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='beneficiaries.beneficiary'),
        ),
        migrations.AddField(
            model_name='beneficiaryindicator',
            name='criterion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='indicators', to='criteria.criterion'),
        ),
        migrations.AddField(
            model_name='beneficiaryindicator',
            name='encoded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encoded_indicators', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='family',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deletions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='family',
            name='encoded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encoded_families', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='family',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_families', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='beneficiaries.family'),
        ),
        migrations.AddField(
            model_name='household',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deletions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='household',
            name='encoded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encoded_households', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='household',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_households', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='family',
            name='household',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='families', to='beneficiaries.household'),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='household',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='direct_members', to='beneficiaries.household'),
        ),
        migrations.AlterUniqueTogether(
            name='beneficiaryindicator',
            unique_together={('beneficiary', 'criterion')},
        ),
        migrations.AlterUniqueTogether(
            name='family',
            unique_together={('household', 'family_number')},
        ),
    ]
