# Generated by Django 6.0.5 on 2026-05-06 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
