# Generated by Django 6.0.5 on 2026-05-25 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0003_beneficiary_first_name_beneficiary_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='electrical_condition',
            field=models.CharField(blank=True, choices=[('legal_canoreco', 'Legally Connected to Electric Utility (CANORECO)'), ('shared_meter', 'Shared Meter / Sub-metered Connection'), ('unauthorized_connection', 'Unauthorized Electrical Connection'), ('no_service', 'No Electrical Service Access'), ('unstable_supply', 'Unstable Electrical Supply')], default='', max_length=35),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='lot_area_sqm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='structure_condition',
            field=models.CharField(blank=True, choices=[('concrete', 'Concrete House (Concrete Structure)'), ('semi_concrete', 'Semi-Concrete House (Concrete and Wood Combination)'), ('wooden', 'Wooden House (Primarily Wood Materials)'), ('light_materials', 'Light Materials House (Nipa, Bamboo, Yero, Plywood, etc.)'), ('mixed_materials', 'Mixed Materials House (Combination of Various Materials)')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='tenure_status',
            field=models.CharField(blank=True, choices=[('homeowner', 'Homeowner'), ('renter_tenant', 'Renter / Tenant'), ('living_with_relatives', 'Living with Relatives'), ('informal_settler', 'Informal Settler'), ('government_housing_beneficiary', 'Government Housing Beneficiary')], default='', max_length=40),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='water_source',
            field=models.CharField(blank=True, choices=[('private_connection', 'Private Water Connection'), ('shared_connection', 'Shared Water Connection'), ('community_system', 'Community Water System'), ('deep_well', 'Deep Well / Own Well'), ('hand_pump', 'Hand Pump'), ('refilling_station', 'Water Refilling Station'), ('no_regular_supply', 'No Regular Water Supply')], default='', max_length=35),
        ),
        migrations.AddField(
            model_name='household',
            name='house_no_or_blk_lot_no',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='household',
            name='landmark',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='household',
            name='length_of_residency',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='household',
            name='purok_sitio',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='household',
            name='street_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='employment_status',
            field=models.CharField(choices=[('unemployed', 'Unemployed'), ('displaced_terminated', 'Displaced/Terminated'), ('underemployed', 'Underemployed'), ('self_employed_informal', 'Self-Employed/Informal'), ('employed', 'Employed'), ('student', 'Student'), ('retired', 'Retired'), ('pwd_unable_to_work', 'PWD / Unable to Work')], default='unemployed', max_length=25),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='housing_condition',
            field=models.CharField(choices=[('makeshift', 'Makeshift/Informal Settler'), ('semi_permanent', 'Semi-Permanent'), ('permanent_deteriorating', 'Permanent but Deteriorating'), ('permanent_good', 'Permanent Good Condition'), ('informal_settler', 'Informal Settler'), ('semi_permanent_housing', 'Semi-Permanent Housing'), ('permanent_good_condition', 'Permanent Housing (Good Condition)'), ('permanent_needs_repair', 'Permanent Housing (Needs Repair)'), ('under_construction', 'Under Construction'), ('condemned_unsafe', 'Condemned / Unsafe Structure')], default='makeshift', max_length=25),
        ),
    ]
