import { useEffect, useMemo, useState } from 'react'
import { cyclesApi } from '../../api/cycles'
import { reportsApi, downloadBlob } from '../../api/reports'

function Icon({ children, size = 18 }) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="1.9"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      {children}
    </svg>
  )
}

const CATEGORY_DETAILS = {
  'Beneficiary Reports': {
    description: 'Resident profile records, eligibility details, and socio-economic fields.',
    tone: 'bg-blue-50 text-blue-700 border-blue-200',
  },
  'Household Reports': {
    description: 'Household, family, and member records grouped into separate worksheets.',
    tone: 'bg-emerald-50 text-emerald-700 border-emerald-200',
  },
  'Participation Reports': {
    description: 'TUPAD participation summaries and daily attendance records.',
    tone: 'bg-amber-50 text-amber-700 border-amber-200',
  },
  'Audit Reports': {
    description: 'System actions, timestamps, users, and affected records.',
    tone: 'bg-slate-50 text-slate-700 border-slate-200',
  },
  'Cycle Ranking Reports': {
    description: 'Cycle-level applicant rankings, scores, status, and criteria values.',
    tone: 'bg-primary-50 text-primary-700 border-primary-200',
  },
}

const REPORTS = [
  {
    id: 'cycle-ranking',
    category: 'Cycle Ranking Reports',
    label: 'Cycle Ranking',
    description: 'Exports ranked applicants for a selected program cycle.',
    source: 'Program cycles, cycle applications, beneficiary criteria indicators',
    includes: ['Rank position', 'Computed score', 'Applicant status', 'Criteria value columns'],
    filename: (cycle) => `cycle_ranking_${safeName(cycle?.cycle_name ?? 'report')}.xlsx`,
    needsCycle: true,
    cycleRequired: true,
    icon: (
      <Icon>
        <line x1="18" y1="20" x2="18" y2="10" />
        <line x1="12" y1="20" x2="12" y2="4" />
        <line x1="6" y1="20" x2="6" y2="14" />
      </Icon>
    ),
  },
  {
    id: 'beneficiary-masterlist',
    category: 'Beneficiary Reports',
    label: 'Beneficiary Masterlist',
    description: 'Exports all resident profiles with demographic, welfare, and eligibility data.',
    source: 'Beneficiary records linked to family and household records',
    includes: ['Name and demographics', 'Employment and sectors', 'Housing data', 'TUPAD eligibility'],
    filename: () => 'beneficiary_masterlist.xlsx',
    icon: (
      <Icon>
        <path d="M20 21v-2a4 4 0 00-4-4H8a4 4 0 00-4 4v2" />
        <circle cx="12" cy="7" r="4" />
      </Icon>
    ),
  },
  {
    id: 'participation-history',
    category: 'Participation Reports',
    label: 'Participation History',
    description: 'Exports participation summaries and daily attendance records per cycle.',
    source: 'Participation records and daily participation attendance',
    includes: ['Project details', 'Days worked', 'Daily status', 'Hours worked and photo links'],
    filename: () => 'participation_history.xlsx',
    needsCycle: true,
    cycleRequired: false,
    icon: (
      <Icon>
        <path d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2" />
        <rect x="9" y="3" width="6" height="4" rx="2" />
        <path d="M9 12l2 2 4-4" />
      </Icon>
    ),
  },
  {
    id: 'audit-trail',
    category: 'Audit Reports',
    label: 'Audit Trail',
    description: 'Exports system activity logs for accountability and review.',
    source: 'Audit log entries generated by system actions',
    includes: ['Timestamp', 'User', 'Action', 'Target table and record', 'Details'],
    filename: () => 'audit_trail.xlsx',
    needsDates: true,
    icon: (
      <Icon>
        <circle cx="11" cy="11" r="8" />
        <line x1="21" y1="21" x2="16.65" y2="16.65" />
      </Icon>
    ),
  },
  {
    id: 'household',
    category: 'Household Reports',
    label: 'Household Registry',
    description: 'Exports households, families, and household members in one workbook.',
    source: 'Household records with related families and resident profiles',
    includes: ['Household address fields', 'Family income bracket', 'Member details', 'Housing utilities'],
    filename: () => 'household_report.xlsx',
    icon: (
      <Icon>
        <path d="M3 9l9-7 9 7v11a2 2 0 01-2 2H5a2 2 0 01-2-2z" />
        <polyline points="9 22 9 12 15 12 15 22" />
      </Icon>
    ),
  },
]

export default function ReportsPage() {
  const [selectedId, setSelectedId] = useState(REPORTS[0].id)
  const [cycles, setCycles] = useState([])
  const [filters, setFilters] = useState({ cycle_id: '', start_date: '', end_date: '' })
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState('')
  const [success, setSuccess] = useState('')

  const selected = REPORTS.find((report) => report.id === selectedId) ?? REPORTS[0]
  const selectedCycle = cycles.find((cycle) => String(cycle.id) === String(filters.cycle_id))
  const categories = useMemo(() => groupReportsByCategory(REPORTS), [])

  useEffect(() => {
    cyclesApi.list({ page_size: 100 })
      .then((data) => setCycles(data.results ?? data))
      .catch(() => setError('Failed to load program cycles. Reports without cycle filters are still available.'))
  }, [])

  const selectReport = (report) => {
    setSelectedId(report.id)
    setError('')
    setSuccess('')
    setFilters({ cycle_id: '', start_date: '', end_date: '' })
  }

  const updateFilter = (name, value) => {
    setFilters((current) => ({ ...current, [name]: value }))
    setError('')
    setSuccess('')
  }

  const handleDownload = async () => {
    const validationError = validateFilters(selected, filters)
    if (validationError) {
      setError(validationError)
      return
    }
    if (!window.confirm(`Generate ${selected.label} report?`)) return

    setLoading(true)
    setError('')
    setSuccess('')

    try {
      const blob = await generateReport(selected, filters)
      downloadBlob(blob, selected.filename(selectedCycle))
      setSuccess(`${selected.label} report was generated.`)
    } catch {
      setError('Failed to generate report. Please check the filters and try again.')
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="max-w-7xl space-y-5">
      <header className="flex flex-col gap-3 lg:flex-row lg:items-end lg:justify-between">
        <div>
          <p className="page-section-label">System Outputs</p>
          <h1 className="mt-1 text-2xl font-bold text-ink-900">Reports</h1>
          <p className="mt-1 max-w-2xl text-sm text-ink-500">
            Generate Excel files for ranking, resident records, households, TUPAD participation, and audit review.
          </p>
        </div>
        <div className="flex flex-wrap gap-2">
          <span className="badge bg-primary-100 text-primary-700">{REPORTS.length} report templates</span>
          <span className="badge bg-slate-100 text-ink-600">{cycles.length} cycles loaded</span>
        </div>
      </header>

      {error && <div className="alert-error">{error}</div>}
      {success && <div className="alert-success">{success}</div>}

      <div className="grid gap-5 xl:grid-cols-[360px_minmax(0,1fr)]">
        <aside className="space-y-4">
          {Object.entries(categories).map(([category, reports]) => {
            const details = CATEGORY_DETAILS[category]
            return (
              <section key={category} className="card">
                <div className={`border-b px-4 py-3 ${details.tone}`}>
                  <h2 className="text-sm font-bold">{category}</h2>
                  <p className="mt-1 text-xs leading-5 opacity-90">{details.description}</p>
                </div>
                <div className="divide-y divide-slate-100">
                  {reports.map((report) => (
                    <button
                      key={report.id}
                      type="button"
                      onClick={() => selectReport(report)}
                      className={`flex w-full items-start gap-3 px-4 py-3 text-left transition hover:bg-slate-50 ${
                        selected.id === report.id ? 'bg-primary-50' : 'bg-white'
                      }`}
                    >
                      <span className={`mt-0.5 flex h-9 w-9 shrink-0 items-center justify-center rounded-lg ${
                        selected.id === report.id ? 'bg-primary-900 text-white' : 'bg-slate-100 text-ink-500'
                      }`}>
                        {report.icon}
                      </span>
                      <span className="min-w-0">
                        <span className={`block text-sm font-semibold ${
                          selected.id === report.id ? 'text-primary-800' : 'text-ink-900'
                        }`}>
                          {report.label}
                        </span>
                        <span className="mt-0.5 block text-xs leading-5 text-ink-500">{report.description}</span>
                      </span>
                    </button>
                  ))}
                </div>
              </section>
            )
          })}
        </aside>

        <main className="space-y-5">
          <section className="card">
            <div className="border-b border-slate-200 bg-slate-50 px-5 py-4">
              <div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between">
                <div>
                  <h2 className="text-lg font-bold text-ink-900">{selected.label}</h2>
                  <p className="mt-1 text-sm text-ink-500">{selected.description}</p>
                </div>
                <span className={`badge border ${CATEGORY_DETAILS[selected.category].tone}`}>{selected.category}</span>
              </div>
            </div>

            <div className="grid gap-5 p-5 lg:grid-cols-[minmax(0,1fr)_280px]">
              <div className="space-y-5">
                <section>
                  <h3 className="text-sm font-bold text-ink-900">Filters</h3>
                  <div className="mt-3 grid gap-4 md:grid-cols-2">
                    {selected.needsCycle && (
                      <Field
                        label="Program Cycle"
                        hint={selected.cycleRequired ? 'Required for this report' : 'Optional filter'}
                      >
                        <select
                          value={filters.cycle_id}
                          onChange={(event) => updateFilter('cycle_id', event.target.value)}
                          className="form-input"
                        >
                          <option value="">{selected.cycleRequired ? 'Select a cycle...' : 'All cycles'}</option>
                          {cycles.map((cycle) => (
                            <option key={cycle.id} value={cycle.id}>{cycle.cycle_name}</option>
                          ))}
                        </select>
                      </Field>
                    )}

                    {selected.needsDates && (
                      <>
                        <Field label="Start Date" hint="Optional">
                          <input
                            type="date"
                            value={filters.start_date}
                            onChange={(event) => updateFilter('start_date', event.target.value)}
                            className="form-input"
                          />
                        </Field>
                        <Field label="End Date" hint="Optional">
                          <input
                            type="date"
                            value={filters.end_date}
                            onChange={(event) => updateFilter('end_date', event.target.value)}
                            className="form-input"
                          />
                        </Field>
                      </>
                    )}

                    {!selected.needsCycle && !selected.needsDates && (
                      <div className="rounded-lg border border-slate-200 bg-slate-50 px-4 py-3 text-sm text-ink-600 md:col-span-2">
                        This report does not need filters. It exports the current records available to your account.
                      </div>
                    )}
                  </div>
                </section>

                <section>
                  <h3 className="text-sm font-bold text-ink-900">Report Contents</h3>
                  <div className="mt-3 grid gap-3 sm:grid-cols-2">
                    {selected.includes.map((item) => (
                      <div key={item} className="flex items-center gap-2 rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm text-ink-700">
                        <svg className="shrink-0 text-emerald-600" width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.4" strokeLinecap="round" strokeLinejoin="round">
                          <path d="M20 6L9 17l-5-5" />
                        </svg>
                        {item}
                      </div>
                    ))}
                  </div>
                </section>

                <div className="flex flex-col gap-3 border-t border-slate-200 pt-5 sm:flex-row sm:items-center">
                  <button
                    type="button"
                    onClick={handleDownload}
                    disabled={loading}
                    className="btn-primary justify-center"
                  >
                    {loading ? (
                      <>
                        <svg className="animate-spin" width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.4">
                          <path d="M21 12a9 9 0 11-18 0 9 9 0 0118 0z" strokeOpacity="0.25" />
                          <path d="M21 12a9 9 0 00-9-9" />
                        </svg>
                        Generating...
                      </>
                    ) : (
                      <>
                        <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.3" strokeLinecap="round" strokeLinejoin="round">
                          <path d="M21 15v4a2 2 0 01-2 2H5a2 2 0 01-2-2v-4" />
                          <polyline points="7 10 12 15 17 10" />
                          <line x1="12" y1="15" x2="12" y2="3" />
                        </svg>
                        Download Excel
                      </>
                    )}
                  </button>
                  <p className="text-xs text-ink-400">A confirmation prompt appears before generating the file.</p>
                </div>
              </div>

              <aside className="space-y-3">
                <InfoBox label="Data Source" value={selected.source} />
                <InfoBox label="Output Type" value="Excel workbook (.xlsx)" />
                <InfoBox label="Filename" value={selected.filename(selectedCycle)} mono />
                {selectedCycle && (
                  <InfoBox
                    label="Selected Cycle"
                    value={`${selectedCycle.cycle_name} | Work: ${selectedCycle.work_start_date || 'N/A'} to ${selectedCycle.work_end_date || 'N/A'}`}
                  />
                )}
              </aside>
            </div>
          </section>
        </main>
      </div>
    </div>
  )
}

function groupReportsByCategory(reports) {
  return reports.reduce((groups, report) => {
    groups[report.category] = [...(groups[report.category] ?? []), report]
    return groups
  }, {})
}

function validateFilters(report, filters) {
  if (report.cycleRequired && !filters.cycle_id) return 'Please select a program cycle.'
  if (filters.start_date && filters.end_date && filters.end_date < filters.start_date) {
    return 'End date cannot be before start date.'
  }
  return ''
}

function generateReport(report, filters) {
  const params = {}
  if (filters.cycle_id) params.cycle_id = filters.cycle_id
  if (filters.start_date) params.start_date = filters.start_date
  if (filters.end_date) params.end_date = filters.end_date

  if (report.id === 'cycle-ranking') return reportsApi.cycleRanking(filters.cycle_id)
  if (report.id === 'beneficiary-masterlist') return reportsApi.beneficiaryMasterlist()
  if (report.id === 'participation-history') return reportsApi.participationHistory(params)
  if (report.id === 'audit-trail') return reportsApi.auditTrail(params)
  if (report.id === 'household') return reportsApi.household()
  return Promise.reject(new Error('Unknown report.'))
}

function safeName(value) {
  return String(value).trim().replace(/\s+/g, '_').replace(/[^a-zA-Z0-9_.-]/g, '') || 'report'
}

function Field({ label, hint, children }) {
  return (
    <label className="block">
      <span className="flex items-center justify-between gap-2">
        <span className="text-sm font-medium text-ink-700">{label}</span>
        {hint && <span className="text-xs text-ink-400">{hint}</span>}
      </span>
      <span className="mt-1 block">{children}</span>
    </label>
  )
}

function InfoBox({ label, value, mono = false }) {
  return (
    <div className="rounded-lg border border-slate-200 bg-slate-50 px-3 py-3">
      <p className="text-[11px] font-semibold uppercase tracking-wider text-ink-400">{label}</p>
      <p className={`mt-1 text-sm font-semibold text-ink-800 ${mono ? 'break-all font-mono text-xs' : 'leading-5'}`}>
        {value}
      </p>
    </div>
  )
}
